### ISSUE TITLE
View epoch contributions

### ISSUE THREAD

**Issue by aahna-ashina** [sector-3/ui#11]

**Comment by brymut** [comment]
Hi @aahna-ashina, came here by way of the task posted on Dework. I'd be more than happy to have a look/take this on if the task is currently available to be taken on

**Comment by frankomosh** [comment]
Cant see the task @aahna-ashina

**Comment by developerfred** [comment]
done here:
https://github.com/sector-3/protocol/pull/34
https://github.com/sector-3/ui/pull/18

🚀
